@echo off
echo Killing any existing Node.js processes...
taskkill /F /IM node.exe >nul 2>&1

echo Cleaning up any existing dist folder...
if exist "client\public\dist" rd /s /q "client\public\dist"

echo Installing dependencies...
call npm install

echo Starting webpack development server...
start "Webpack Dev Server" cmd /c "npm start"

echo Done! The game should be available at http://localhost:3000
echo Press any key to close this window...
pause >nul
